In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Import Datasets (Bayer-Flamsteed-Cross Index, Hipparcos Dataset and Star Names)
===
Bayer-Flamsteed-Cross Index (IV/27A/catalog) from https://vizier.cds.unistra.fr/viz-bin/VizieR-3?-source=IV/27A/catalog

Hipparcos-Datasset (I/239/hip_main) from https://vizier.cds.unistra.fr/viz-bin/VizieR-2

Star-Names generated/obtained by Eike

In [23]:
#Import Datasets

#Bayer-Flamsteed-Cross Index
bfi = pd.read_csv("bayer_flamsteed_cross.csv")

#Hipparcos-Dataset
hip = pd.read_csv("hipparcos.csv")

#Star Names by Eike
star_names = pd.read_csv("star_names.csv")

Dataset Preprocessing
===

In [3]:
#Set Datatype to Pandas Int and Index by HIP-Column
bfi["HIP"] = bfi["HIP"].astype("Int64")
bfi = bfi.set_index("HIP")
bfi

,n_HD,HD,DM,GC,HR,RAJ2000,DEJ2000,Vmag,Fl,Bayer,Cst,SimbadName
HIP,,,,,,,,,,,,
14135,M,18884,BD+03 419,3643.0,911.0,45.569917,4.089917,2.54,92.0,alf,Cet,HD 18884
14143,,18883,BD+03 420,3646.0,910.0,45.593792,4.352861,5.62,93.0,,Cet,HD 18883
14915,,19926,BD+06 496A,3827.0,958.0,48.109875,6.660889,5.55,NaN,g,Tau,HD 19926
13954,M,18604,BD+08 455,3595.0,896.0,44.928750,8.907389,4.71,91.0,lam,Cet,HD 18604
15900,,21120,BD+08 511,4070.0,1030.0,51.203500,9.029056,3.61,1.0,omi,Tau,HD 21120
...,...,...,...,...,...,...,...,...,...,...,...,...
105164,,202753,BD-05 5512,29793.0,8141.0,319.546125,-4.519500,5.83,15.0,,Aqr,HD 202753
103682,,199960,BD-05 5433,29318.0,8041.0,315.140875,-4.729917,6.21,11.0,,Aqr,HD 199960
102945,,198571,BD-06 5604,29078.0,7982.0,312.857042,-5.626639,5.99,4.0,,Aqr,HD 198571
103005,,198667,BD-06 5606,29094.0,7985.0,313.036208,-5.507056,5.55,5.0,,Aqr,HD 198667
102624,,198026,BD-05 5378,28979.0,7951.0,311.934333,-5.027611,4.43,3.0,k,Aqr,HD 198026

In [4]:
#Index by HIP-Column
hip = hip.set_index("HIP")
hip

,RAhms,DEdms,Vmag,RAICRS,DEICRS,Plx,pmRA,pmDE,e_Plx,B-V,Notes,_RA_icrs,_DE_icrs
HIP,,,,,,,,,,,,,
1,00 00 00.22,+01 05 20.4,9.10,0.000912,1.089013,3.54,-5.20,-1.88,1.39,0.482,,0.000899,1.089009
2,00 00 00.91,-19 29 55.8,9.27,0.003797,-19.498837,21.90,181.21,-0.93,3.10,0.999,,0.004265,-19.498840
3,00 00 01.20,+38 51 33.4,6.61,0.005008,38.859286,2.81,5.24,-2.91,0.63,-0.019,,0.005024,38.859279
4,00 00 02.01,-51 53 36.8,8.06,0.008382,-51.893546,7.75,62.85,0.16,0.97,0.370,,0.008629,-51.893546
5,00 00 02.39,-40 35 28.4,8.55,0.009965,-40.591224,2.87,2.53,9.07,1.11,0.902,,0.009973,-40.591202
...,...,...,...,...,...,...,...,...,...,...,...,...,...
118318,23 59 51.30,+11 40 25.4,6.99,359.963744,11.673709,1.92,-2.16,2.09,0.91,1.595,,359.963738,11.673714
118319,23 59 53.74,-22 25 41.4,8.23,359.973913,-22.428180,10.63,148.74,27.53,1.17,0.639,,359.974304,-22.428113
118320,23 59 54.25,+05 57 23.9,7.59,359.976057,5.956638,5.00,20.92,-35.26,1.01,0.999,,359.976109,5.956552
118321,23 59 54.78,-64 22 21.3,9.20,359.978239,-64.372572,19.22,216.99,106.46,1.00,0.698,,359.979458,-64.372313
118322,23 59 54.91,-65 34 37.5,4.49,359.978792,-65.577078,8.71,48.63,-22.33,0.57,-0.075,,359.979078,-65.577132

In [5]:
#Print NaN's
nans = bfi[bfi.index.isnull()]
nans

,n_HD,HD,DM,GC,HR,RAJ2000,DEJ2000,Vmag,Fl,Bayer,Cst,SimbadName
HIP,,,,,,,,,,,,
<NA>,X,23629,BD+23 536,4536.0,NaN,56.837083,24.116111,6.30,24.0,,Tau,HD 23629
<NA>,,23607,BD+23 534,NaN,NaN,56.830000,24.139444,8.30,NaN,eta,Tau,HD 23607
<NA>,X,11503,BD+18 243A,2291.0,545.0,28.382500,19.295833,4.83,5.0,gam02,Ari,HD 11503
<NA>,,11155,BD+21 243B,NaN,NaN,27.535417,22.275833,5.90,1.0,,Ari,HD 11155
<NA>,M,18520,BD+20 484B,NaN,888.0,44.802917,21.340278,4.63,48.0,eps,Ari,HD 18520
...,...,...,...,...,...,...,...,...,...,...,...,...
<NA>,,108925,CP-56 5274,17055.0,4764.0,187.819583,-57.081111,6.42,NaN,gam,Cru,HD 108925
<NA>,,120710,CD-32 9676B,18725.0,5211.0,207.958750,-32.994722,6.06,3.0,k,Cen,HD 120710
<NA>,X,145501,BD-19 4332,21771.0,6026.0,242.994167,-19.449722,6.30,14.0,nu.,Sco,HD 145501
<NA>,,177475,CD-37 13048B,NaN,7227.0,286.604583,-37.063333,4.99,NaN,gam,CrA,HD 177475
<NA>,,200497,BD-06 5664A,29417.0,8059.0,316.019583,-5.823056,5.89,12.0,,Aqr,HD 200497

In [6]:
#Remove NaN's
bfi = bfi[np.invert(bfi.index.isnull())]
bfi

,n_HD,HD,DM,GC,HR,RAJ2000,DEJ2000,Vmag,Fl,Bayer,Cst,SimbadName
HIP,,,,,,,,,,,,
14135,M,18884,BD+03 419,3643.0,911.0,45.569917,4.089917,2.54,92.0,alf,Cet,HD 18884
14143,,18883,BD+03 420,3646.0,910.0,45.593792,4.352861,5.62,93.0,,Cet,HD 18883
14915,,19926,BD+06 496A,3827.0,958.0,48.109875,6.660889,5.55,NaN,g,Tau,HD 19926
13954,M,18604,BD+08 455,3595.0,896.0,44.928750,8.907389,4.71,91.0,lam,Cet,HD 18604
15900,,21120,BD+08 511,4070.0,1030.0,51.203500,9.029056,3.61,1.0,omi,Tau,HD 21120
...,...,...,...,...,...,...,...,...,...,...,...,...
105164,,202753,BD-05 5512,29793.0,8141.0,319.546125,-4.519500,5.83,15.0,,Aqr,HD 202753
103682,,199960,BD-05 5433,29318.0,8041.0,315.140875,-4.729917,6.21,11.0,,Aqr,HD 199960
102945,,198571,BD-06 5604,29078.0,7982.0,312.857042,-5.626639,5.99,4.0,,Aqr,HD 198571
103005,,198667,BD-06 5606,29094.0,7985.0,313.036208,-5.507056,5.55,5.0,,Aqr,HD 198667
102624,,198026,BD-05 5378,28979.0,7951.0,311.934333,-5.027611,4.43,3.0,k,Aqr,HD 198026

In [7]:
#Cast HIP-Column to Int. When impossible, drop row
star_names["HIP"] = pd.to_numeric(star_names["HIP"], errors="coerce")
star_names = star_names.dropna(subset=["HIP"])

#Drop old arbitrary Index-Column
star_names = star_names.drop("Unnamed: 0", axis=1).set_index("HIP")
star_names

,IAU Name,Designation,Bayer Name,#,WDS_J,Vmag,RA(J2000),Dec(J2000),Origin,Etymology Note,Source,Unnamed: 13,ID,Const.
HIP,,,,,,,,,,,,,,
13847.0,Acamar,HR 897,θ1 Eri,A,02583-4018,2.88,44.565311,-40.304672,NaN,NaN,NaN,NaN,θ1,Eri
7588.0,Achernar,HR 472,α Eri,A,-,0.45,24.428523,-57.236753,Arabic,The name was originally Arabic: آخر النهر ʾāẖi...,NaN,NaN,α,Eri
3821.0,Achird,HR 219,η Cas,A,00491+5749,3.46,12.276213,57.815187,NaN,first applied to η Cassiopeiae in the Skalnate...,NaN,NaN,η,Cas
78820.0,Acrab,HR 5984,β1 Sco,Aa,16054-1948,2.56,241.359300,-19.805453,Arabic,the traditional name of the β Scorpii system h...,NaN,NaN,β1,Sco
60718.0,Acrux,HR 4730,α Cru,Aa,12266-6306,1.33,186.649563,-63.099093,"""Americanism""","a modern contraction of the Bayer designation,...",NaN,NaN,α,Cru
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15197.0,Zibal,HR 984,ζ Eri,Aa,03158-0849,4.80,48.958436,-8.819731,NaN,NaN,NaN,NaN,ζ,Eri
54872.0,Zosma,HR 4357,δ Leo,-,11141+2031,2.56,168.527089,20.523718,NaN,NaN,NaN,NaN,δ,Leo
72622.0,Zubenelgenubi,HR 5531,α2 Lib,Aa,14509-1603,2.75,222.719638,-16.041777,NaN,NaN,NaN,NaN,α2,Lib
76333.0,Zubenelhakrabi,HR 5787,γ Lib,A,15355-1447,3.91,233.881578,-14.789536,NaN,NaN,NaN,NaN,γ,Lib
74785.0,Zubeneschamali,HR 5685,β Lib,-,-,2.61,229.251724,-9.382914,NaN,NaN,NaN,NaN,β,Lib

In [8]:
#Rename "IAU Name " to "name"
star_names = star_names.rename({"IAU Name ": "name"}, axis=1)
star_names = pd.DataFrame(star_names["name"])
star_names

                   name
HIP
13847.0          Acamar
7588.0         Achernar
3821.0           Achird
78820.0           Acrab
60718.0           Acrux
...                 ...
15197.0           Zibal
54872.0           Zosma
72622.0   Zubenelgenubi
76333.0  Zubenelhakrabi
74785.0  Zubeneschamali

[408 rows x 1 columns]

Join Datasets
===
1. Join Hipparcos with Bayer-Flamsteed-Cross Index
2. Calculate Distance from Parallax
3. Calculate X, Y, Z Coordinates from Equatorial Coordinates
4. Join Result with star_names

In [9]:
#Join Hipparcos-Catalog and Bayer-Flamsteed-Cross Index
joined = bfi.join(hip, lsuffix="_bfi", rsuffix="_hip", how="left")
joined

,n_HD,HD,DM,GC,HR,RAJ2000,DEJ2000,Vmag_bfi,Fl,Bayer,...,RAICRS,DEICRS,Plx,pmRA,pmDE,e_Plx,B-V,Notes,_RA_icrs,_DE_icrs
HIP,,,,,,,,,,,,,,,,,,,,,
14135,M,18884,BD+03 419,3643.0,911.0,45.569917,4.089917,2.54,92.0,alf,...,45.569913,4.089925,14.82,-11.81,-78.76,0.83,1.630,P,45.569884,4.089734
14143,,18883,BD+03 420,3646.0,910.0,45.593792,4.352861,5.62,93.0,,...,45.593784,4.352870,7.32,16.70,5.64,0.80,-0.107,,45.593825,4.352884
14915,,19926,BD+06 496A,3827.0,958.0,48.109875,6.660889,5.55,NaN,g,...,48.109875,6.660886,4.18,-8.09,-1.26,0.86,1.011,,48.109855,6.660883
13954,M,18604,BD+08 455,3595.0,896.0,44.928750,8.907389,4.71,91.0,lam,...,44.928735,8.907401,7.69,9.22,-14.92,0.76,-0.109,,44.928757,8.907365
15900,,21120,BD+08 511,4070.0,1030.0,51.203500,9.029056,3.61,1.0,omi,...,51.203490,9.029065,15.42,-74.25,-80.31,1.28,0.887,,51.203307,9.028870
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105164,,202753,BD-05 5512,29793.0,8141.0,319.546125,-4.519500,5.83,15.0,,...,319.546108,-4.519512,3.33,11.82,13.69,0.86,-0.130,,319.546137,-4.519478
103682,,199960,BD-05 5433,29318.0,8041.0,315.140875,-4.729917,6.21,11.0,,...,315.140884,-4.729924,37.80,47.64,-138.75,1.01,0.635,,315.141000,-4.730261
102945,,198571,BD-06 5604,29078.0,7982.0,312.857042,-5.626639,5.99,4.0,,...,312.857051,-5.626636,16.97,95.77,1.25,1.26,0.464,,312.857285,-5.626633
103005,,198667,BD-06 5606,29094.0,7985.0,313.036208,-5.507056,5.55,5.0,,...,313.036221,-5.507044,4.33,1.26,-6.20,1.08,-0.076,,313.036225,-5.507059
102624,,198026,BD-05 5378,28979.0,7951.0,311.934333,-5.027611,4.43,3.0,k,...,311.934325,-5.027603,7.33,-3.30,-40.24,0.99,1.639,,311.934317,-5.027701

In [10]:
#Remove Rows that have no Plx and thus no Distance can be calculated
joined = joined[np.invert(joined["Plx"].isnull())]
joined["Plx"].isnull().any()

False

In [11]:
def calc_distance(plx):
    return 1 / (plx / 1000)

In [12]:
#Calculate Distance in Parsecs for all stars
joined["distance"] = calc_distance(joined["Plx"])
joined

/tmp/ipykernel_23420/1363166962.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  joined["distance"] = calc_distance(joined["Plx"])

,n_HD,HD,DM,GC,HR,RAJ2000,DEJ2000,Vmag_bfi,Fl,Bayer,...,DEICRS,Plx,pmRA,pmDE,e_Plx,B-V,Notes,_RA_icrs,_DE_icrs,distance
HIP,,,,,,,,,,,,,,,,,,,,,
14135,M,18884,BD+03 419,3643.0,911.0,45.569917,4.089917,2.54,92.0,alf,...,4.089925,14.82,-11.81,-78.76,0.83,1.630,P,45.569884,4.089734,67.476383
14143,,18883,BD+03 420,3646.0,910.0,45.593792,4.352861,5.62,93.0,,...,4.352870,7.32,16.70,5.64,0.80,-0.107,,45.593825,4.352884,136.612022
14915,,19926,BD+06 496A,3827.0,958.0,48.109875,6.660889,5.55,NaN,g,...,6.660886,4.18,-8.09,-1.26,0.86,1.011,,48.109855,6.660883,239.234450
13954,M,18604,BD+08 455,3595.0,896.0,44.928750,8.907389,4.71,91.0,lam,...,8.907401,7.69,9.22,-14.92,0.76,-0.109,,44.928757,8.907365,130.039012
15900,,21120,BD+08 511,4070.0,1030.0,51.203500,9.029056,3.61,1.0,omi,...,9.029065,15.42,-74.25,-80.31,1.28,0.887,,51.203307,9.028870,64.850843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105164,,202753,BD-05 5512,29793.0,8141.0,319.546125,-4.519500,5.83,15.0,,...,-4.519512,3.33,11.82,13.69,0.86,-0.130,,319.546137,-4.519478,300.300300
103682,,199960,BD-05 5433,29318.0,8041.0,315.140875,-4.729917,6.21,11.0,,...,-4.729924,37.80,47.64,-138.75,1.01,0.635,,315.141000,-4.730261,26.455026
102945,,198571,BD-06 5604,29078.0,7982.0,312.857042,-5.626639,5.99,4.0,,...,-5.626636,16.97,95.77,1.25,1.26,0.464,,312.857285,-5.626633,58.927519
103005,,198667,BD-06 5606,29094.0,7985.0,313.036208,-5.507056,5.55,5.0,,...,-5.507044,4.33,1.26,-6.20,1.08,-0.076,,313.036225,-5.507059,230.946882
102624,,198026,BD-05 5378,28979.0,7951.0,311.934333,-5.027611,4.43,3.0,k,...,-5.027603,7.33,-3.30,-40.24,0.99,1.639,,311.934317,-5.027701,136.425648

In [13]:
#Calculate XYZ (Cartesian Coordinates) from Equatorial Coordinates
#X, Y, Z are in Parsecs
#r: radius, phi: right ascension, theta: declination
def rpt_to_x(r, phi, theta):
    return r * np.sin(np.radians(theta + 90)) * np.cos(np.radians(phi))

def rpt_to_y(r, phi, theta):
    return r * np.sin(np.radians(theta + 90)) * np.sin(np.radians(phi))

def rpt_to_z(r, phi, theta):
    return r * np.cos(np.radians(theta + 90))

joined["x"] = rpt_to_x(joined["distance"], joined["RAJ2000"], joined["DEJ2000"])
joined["y"] = rpt_to_y(joined["distance"], joined["RAJ2000"], joined["DEJ2000"])
joined["z"] = rpt_to_z(joined["distance"], joined["RAJ2000"], joined["DEJ2000"])

/tmp/ipykernel_23420/1622649263.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  joined["x"] = rpt_to_x(joined["distance"], joined["RAJ2000"], joined["DEJ2000"])
/tmp/ipykernel_23420/1622649263.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  joined["y"] = rpt_to_y(joined["distance"], joined["RAJ2000"], joined["DEJ2000"])
/tmp/ipykernel_23420/1622649263.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  joined["z"] = rpt_to_z(joined["distance"], joined["RAJ2000"], joined["DEJ2000"])

In [14]:
#Join with star_names
joined = joined.join(star_names)

Export Constellations-Dataset
===

In [15]:
#Export Dataset
joined.to_csv("constellations_dataset.csv")
#For exporting only specific columns
#joined.loc[:, ["HD", "RAJ2000", "DEJ2000", "distance", "x", "y", "z"]].to_csv("constellations_dataset_cropped_columns.csv")

Generate Connections for Constellations-Dataset
===

`conns` contains all Connections between Stars in Bayer-Notation

In [16]:
conns_bayer = {
    'Cet': [("alf", "lam"), ("lam", "mu."), ("mu.", "ksi02"), ("ksi02", "nu."), ("nu.", "gam"), ("gam", "alf"), ("gam", "del"), ("del", "omi"), ("omi", "zet"), ("zet", "tau"), ("tau", "bet"), ("bet", "iot"), ("iot", "eta"), ("eta", "the"), ("the", "zet")],
    'Tau': [("bet", "eps"), ("eps", "del"), ("del", "gam"), ("gam", "the01"), ("the01", "alf"), ("alf", "zet"), ("gam", "lam"), ("lam", "ksi"), ("ksi", "nu.")],
    'Ari': [("alf", "bet"), ("bet", "gam01")],
    'Psc': [("tau", "ups"), ("ups", "phi"), ("phi", "tau"), ("phi", "eta"), ("eta", "omi"), ("omi", "alf"), ("alf", "nu."), ("nu.", "mu."), ("mu.", "eps"), ("eps", "del"), ("del", "ome"), ("ome", "iot"), ("iot", "lam"), ("lam", "kap"), ("kap", "gam"), ("gam", "the"), ("the", "iot")],
    'Tri': [("gam", "bet"), ("bet", "alf"), ("alf", "gam")],
    'Per': [("lam", "mu."), ("mu.", "del"), ("del", "eps"), ("eps", "bet"), ("bet", "kap"), ("kap", "iot"), ("iot", "alf"), ("alf", "del"), ("eps", "ksi"), ("ksi", "zet"), ("zet", "omi"), ("bet", "rho"), ("iot", "the"), ("the", "phi"), ("alf", "gam"), ("gam", "eta"), ("eta", "tau"), ("tau", "gam"), ("tau", "iot")],
    'Aur': [("the", "bet"), ("bet", "del"), ("del", "alf"), ("alf", "eps"), ("eps", "zet"), ("zet", "eta"), ("alf", "eta"), ("eta", "iot")],
    'Cam': [("bet", "alf"), ("alf", "gam")],
    'And': [("gam01", "bet"), ("bet", "mu."), ("mu.", "nu."), ("nu.", "phi"), ("bet", "del"), ("del", "pi."), ("pi.", "bet"), ("pi.", "iot"), ("iot", "kap"), ("kap", "lam"), ("iot", "omi"), ("del", "alf"), ("del", "eps"), ("eps", "zet"), ("zet", "eta")],
    'Cas': [("eps", "del"), ("del", "gam"), ("gam", "alf"), ("alf", "bet")],
    'Cep': [("gam", "iot"), ("iot", "bet"), ("bet", "gam"), ("bet", "alf"), ("alf", "eta"), ("eta", "the"), ("alf", "mu."), ("mu.", "eps"), ("eps", "zet"), ("zet", "del"), ("del", "iot")],
    'UMi': [("alf", "del"), ("del", "eps"), ("eps", "zet"), ("zet", "bet"), ("bet", "gam"), ("gam", "eta"), ("eta", "zet")],
    'Hya': [("pi.", "gam"), ("gam", "bet"), ("bet", "ksi"), ("ksi", "nu."), ("nu.", "mu."), ("mu.", "lam"), ("lam", "ups02"), ("ups02", "ups01"), ("ups01", "alf"), ("alf", "iot"), ("iot", "the"), ("the", "zet"), ("zet", "eps"), ("eps", "del"), ("del", "sig"), ("sig", "eta"), ("eta", "rho"), ("rho", "eps")],
    'Leo': [("bet", "the"), ("the", "del"), ("del", "bet"), ("the", "iot"), ("iot", "sig"), ("the", "eta"), ("del", "gam01"), ("gam01", "zet"), ("zet", "mu."), ("mu.", "eps"), ("eps", "eta"), ("mu.", "kap"), ("kap", "lam"), ("lam", "eps"), ("eta", "alf")],
    'Cnc': [("alf", "del"), ("del", "gam"), ("gam", "iot"), ("del", "bet")],
    'Gem': [("ksi", "lam"), ("lam", "del"), ("gam", "zet"), ("zet", "del"), ("del", "ups"), ("ups", "kap"), ("ups", "bet"), ("ups", "iot"), ("iot", "tau"), ("tau", "alf"), ("tau", "the"), ("tau", "eps"), ("eps", "nu."), ("eps", "mu."), ("mu.", "eta")],
    'Lyn': [],
    'LMi': [],
    'UMa': [("eta", "zet"), ("eta", "eps"), ("eps", "del"), ("del", "gam"), ("gam", "chi"), ("chi", "nu."), ("chi", "psi"), ("psi", "mu."), ("mu.", "lam"), ("gam", "bet"), ("bet", "alf"), ("alf", "del"), ("bet", "ups"), ("ups", "omi"), ("ups", "the"), ("the", "kap"), ("kap", "iot")],
    'Dra': [("eps", "del"), ("del", "ksi"), ("ksi", "nu.01"), ("nu.01", "bet"), ("bet", "gam"), ("gam", "ksi"), ("del", "phi"), ("phi", "chi"), ("phi", "zet"), ("zet", "eta"), ("eta", "the"), ("the", "iot"), ("iot", "alf"), ("alf", "kap"), ("kap", "lam")],
    'Vir': [("tau", "zet"), ("zet", "iot"), ("iot", "mu."), ("zet", "gam"), ("gam", "del"), ("del", "eps"), ("gam", "the"), ("the", "alf"), ("gam", "eta"), ("eta", "omi"), ("omi", "nu."), ("nu.", "bet"), ("bet", "eta")],
    'Ser': [],  
    'Boo': [("zet", "alf"), ("tau", "eta"), ("eta", "alf"), ("alf", "eps"), ("eps", "del"), ("del", "bet"), ("bet", "gam"), ("gam", "rho"), ("rho", "alf"), ("gam", "lam"), ("lam", "the"), ("the", "kap01"), ("kap01", "lam")],
    'Her': [("omi", "ksi"), ("ksi", "mu."), ("mu.", "lam"), ("lam", "del"), ("del", "alf01"), ("alf01", "bet"), ("bet", "gam"), ("gam", "ome"), ("bet", "zet"), ("zet", "eps"), ("eps", "del"), ("eps", "pi."), ("pi.", "rho"), ("rho", "the"), ("the", "iot"), ("pi.", "eta"), ("eta", "zet"), ("eta", "sig"), ("sig", "tau"), ("tau", "phi"), ("phi", "chi")],
    'CrB': [("iot", "eps"), ("eps", "del"), ("del", "gam"), ("gam", "alf"), ("alf", "bet"), ("bet", "the")],
    'Com': [("alf", "bet"), ("bet", "gam")],
    'CVn': [("alf01", "bet")],
    'Equ': [("alf", "del"), ("del", "gam")],
    'Del': [("eps", "bet"), ("bet", "del"), ("del", "gam01"), ("gam01", "alf"), ("alf", "bet")],
    'Peg': [("gam", "psi"), ("psi", "bet"), ("bet", "alf"), ("alf", "gam"), ("alf", "zet"), ("zet", "the"), ("the", "eps"), ("bet", "mu."), ("mu.", "lam"), ("lam", "iot"), ("iot", "kap"), ("bet", "eta"), ("eta", "pi.")],
    'Vul': [],
    'Cyg': [("zet", "nu."), ("nu.", "alf"), ("alf", "gam"), ("gam", "eps"), ("eps", "zet"), ("alf", "iot"), ("iot", "kap"), ("iot", "del"), ("del", "gam"), ("gam", "bet01")],
    'Sge': [("gam", "del"), ("del", "bet"), ("del", "alf")],
    'Aql': [("bet", "alf"), ("alf", "gam"), ("gam", "del"), ("del", "eta"), ("eta", "the"), ("the", "iot"), ("iot", "lam"), ("lam", "del"), ("lam", "zet"), ("zet", "eps"), ("zet", "del")],
    'Lac': [],
    'Lyr': [("gam", "bet"), ("bet", "zet01"), ("zet01", "del01"), ("del01", "gam"), ("zet01", "eps01"), ("eps01", "alf"), ("alf", "zet01")],
    'Scl': [("alf", "del"), ("del", "gam"), ("gam", "bet")],
    'Aqr': [("psi02", "phi"), ("phi", "lam"), ("lam", "tau01"), ("tau01", "del"), ("del", "psi02"), ("lam", "the"), ("the", "alf"), ("alf", "pi."), ("pi.", "zet01"), ("zet01", "eta"), ("zet01", "gam"), ("gam", "alf"), ("alf", "bet"), ("bet", "iot"), ("bet", "mu."), ("mu.", "eps")],
    'Cap': [("alf01", "alf02"), ("alf02", "bet"), ("bet", "psi"), ("psi", "ome"), ("ome", "zet"), ("zet", "eps"), ("eps", "del"), ("del", "gam"), ("gam", "the"), ("the", "alf01")],
    'Col': [("eps", "alf"), ("alf", "bet"), ("bet", "eta"), ("bet", "gam"), ("gam", "del")],
    'CMa': [("eta", "del"), ("del", "eps"), ("eps", "omi01"), ("omi01", "nu.02"), ("nu.02", "bet"), ("bet", "alf"), ("alf", "del"), ("alf", "iot"), ("iot", "gam"), ("gam", "the"), ("the", "iot")],
    'Lep': [("alf", "bet"), ("bet", "gam"), ("gam", "del"), ("del", "the"), ("the", "eta"), ("eta", "zet"), ("zet", "alf"), ("alf", "mu."), ("mu.", "lam"), ("mu.", "kap"), ("mu.", "eps"), ("eps", "bet")],
    'Eri': [("alf", "chi"), ("chi", "kap"), ("kap", "iot"), ("iot", "the01"), ("the01", "ups02"), ("ups02", "ups01"), ("ups01", "tau09"), ("tau09", "tau08"), ("tau08", "tau06"), ("tau06", "tau05"), ("tau05", "tau04"), ("tau04", "tau03"), ("tau03", "tau01"), ("tau01", "eta"), ("eta", "eps"), ("eps", "del"), ("del", "pi."), ("pi.", "gam"), ("gam", "omi01"), ("omi01", "nu."), ("nu.", "mu."), ("mu.", "bet")],  
    'Mon': [("alf", "zet"), ("zet", "del"), ("del", "bet"), ("bet", "gam")],
    'Ori': [("kap", "zet"), ("zet", "eps"), ("eps", "del"), ("del", "eta"), ("eta", "bet"), ("zet", "alf"), ("alf", "gam"), ("gam", "del"), ("alf", "lam"), ("lam", "gam"), ("alf", "mu."), ("mu.", "ksi"), ("ksi", "chi02"), ("chi02", "chi01"), ("chi01", "nu."), ("nu.", "ksi"), ("gam", "pi.03"), ("omi02", "pi.01"), ("pi.01", "pi.02"), ("pi.02", "pi.03"), ("pi.03", "pi.04"), ("pi.04", "pi.05"), ("pi.05", "pi.06")],
    'Pup': [("nu.", "pi."), ("pi.", "ksi"), ("ksi", "rho"), ("rho", "zet"), ("ksi", "omi")], 
    'CMi': [("alf", "bet")],
    'Cen': [("alf", "bet"), ("bet", "eps"), ("eps", "gam"), ("gam", "zet"), ("zet", "eps"), ("gam", "sig"), ("sig", "rho"), ("rho", "omi01"), ("sig", "del"), ("del", "pi."), ("zet", "ups01"), ("ups01", "phi"), ("phi", "chi"), ("chi", "psi"), ("psi", "the"), ("the", "nu."), ("nu.", "mu."), ("mu.", "zet"), ("phi", "eta"), ("eta", "kap"), ("nu.", "iot")],
    'Crv': [("alf", "eps"), ("eps", "gam"), ("gam", "del"), ("del", "bet"), ("bet", "eps")],
    'Crt': [("alf", "bet"), ("bet", "gam"), ("gam", "zet"), ("zet", "eta"), ("gam", "del"), ("del", "alf"), ("del", "eps"), ("eps", "the")],
    'Sex': [("del", "bet"), ("bet", "alf"), ("alf", "gam")],
    'Sgr': [("eta", "eps"), ("eps", "zet"), ("zet", "phi"), ("phi", "del"), ("del", "eps"), ("zet", "tau"), ("tau", "sig"), ("sig", "phi"), ("phi", "lam"), ("lam", "del"), ("lam", "mu."), ("del", "gam"), ("gam", "eps")],
    'Sco': [("lam", "ups"), ("ups", "kap"), ("kap", "iot01"), ("iot01", "the"), ("the", "eta"), ("eta", "mu.01"), ("mu.01", "eps"), ("eps", "tau"), ("tau", "alf"), ("alf", "sig"), ("sig", "del"), ("del", "bet01"), ("bet01", "nu."), ("del", "pi."), ("pi.", "rho")],
    'Oph': [("the", "eta"), ("eta", "bet"), ("bet", "gam"), ("gam", "nu."), ("nu.", "tau"), ("bet", "alf"), ("alf", "kap"), ("kap", "zet"), ("zet", "eta"), ("kap", "lam"), ("lam", "del"), ("del", "eps"), ("eps", "ups"), ("ups", "zet"), ("zet", "phi"), ("phi", "chi"), ("chi", "psi"), ("psi", "rho")],
    'Sct': [("alf", "bet"), ("bet", "del"), ("del", "gam"), ("gam", "alf")],
    'Lib': [("tau", "ups"), ("ups", "gam"), ("gam", "bet"), ("bet", "alf01"), ("alf01", "gam"), ("alf01", "sig")],
    'Men': [],
    'Hyi': [("alf", "bet"), ("bet", "gam"), ("gam", "alf")],
    'Oct': [("bet", "nu."), ("nu.", "del"), ("del", "bet")],
    'Dor': [("del", "bet"), ("bet", "zet"), ("zet", "alf"), ("bet", "alf"), ("alf", "gam")],
    'Ret': [("alf", "bet"), ("bet", "del"), ("del", "eps"), ("eps", "alf")],
    'Tuc': [("alf", "del"), ("del", "eps"), ("eps", "zet"), ("zet", "bet01"), ("bet01", "gam"), ("gam", "alf")],
    'Hor': [("alf", "iot"), ("iot", "eta"), ("eta", "zet"), ("zet", "mu."), ("mu.", "bet")],
    'Pic': [("alf", "gam"), ("gam", "bet")],
    'Cae': [("gam", "bet"), ("bet", "alf"), ("alf", "del")],
    'For': [("alf", "bet"), ("bet", "nu.")],
    'Phe': [("alf", "eps"), ("eps", "bet"), ("bet", "alf"), ("bet", "zet"), ("zet", "del"), ("del", "gam"), ("gam", "bet")],
    'Cha': [("alf", "gam"), ("gam", "eps"), ("eps", "bet"), ("bet", "del01"), ("del01", "gam")],
    'Car': [("alf", "bet"), ("bet", "ome"), ("ome", "the"), ("the", "iot"), ("iot", "eps"), ("eps", "chi")],
    'Vol': [("alf", "bet"), ("bet", "eps"), ("eps", "alf"), ("eps", "del"), ("del", "gam01"), ("gam01", "eps")],
    'Mus': [("lam", "eps"), ("eps", "alf"), ("alf", "gam"), ("gam", "del"), ("del", "bet"), ("bet", "alf")],
    'Vel': [("del", "kap"), ("kap", "phi"), ("phi", "mu."), ("mu.", "psi"), ("psi", "lam")],
    'Ant': [("iot", "alf"), ("alf", "eps")],
    'Pyx': [("gam", "alf"), ("alf", "bet")],
    'Aps': [("del01", "gam"), ("gam", "bet"), ("bet", "del01"), ("del01", "alf")],
    'TrA': [("alf", "bet"), ("bet", "gam"), ("gam", "alf")],
    'Nor': [("gam01", "eps"), ("eps", "del"), ("del", "eta"), ("eta", "gam01")],
    'Cir': [("bet", "alf"), ("alf", "gam")],
    'Lup': [("alf", "zet"), ("zet", "eta"), ("eta", "gam"), ("gam", "eps"), ("eps", "mu."), ("mu.", "zet"), ("zet", "alf"), ("gam", "del"), ("del", "bet"), ("eta", "chi"), ("chi", "phi01"), ("phi01", "eta")],
    'Pav': [("zet", "del"), ("eps", "del"), ("del", "bet"), ("bet", "gam"), ("gam", "alf"), ("alf", "del"), ("del", "lam"), ("lam", "ksi"), ("ksi", "pi."), ("pi.", "eta"), ("pi.", "kap"), ("kap", "del")],
    'Ara': [("bet", "alf"), ("the", "alf"), ("alf", "eps01"), ("eps01", "zet"), ("zet", "eta"), ("eta", "del"), ("del", "gam")],
    'Cru': [("alf01", "gam"), ("bet", "del")],
    'Ind': [("alf", "eta"), ("eta", "bet"), ("bet", "del"), ("del", "the"), ("the", "alf")],
    'Tel': [("zet", "alf"), ("alf", "eps")],
    'Gru': [("zet", "eps"), ("eps", "bet"), ("bet", "del01"), ("del01", "alf"), ("alf", "bet"), ("del01", "mu.01"), ("mu.01", "lam"), ("lam", "gam")],
    'PsA': [("alf", "eps"), ("eps", "mu."), ("mu.", "the"), ("the", "iot"), ("iot", "mu."), ("mu.", "bet"), ("bet", "gam"), ("gam", "del"), ("del", "alf")],
    'Mic': [],
    'CrA': [("gam", "alf"), ("alf", "bet"), ("bet", "del"), ("del", "the")]
}

In [17]:
#Check that all Stars in the Connections in Bayer-Notation do also exist in the Constellations-Dataset

#For each Celestial
for starsign in conns_bayer.keys():
    
    #For each Connection in the Celestial
    for item in conns_bayer[starsign]:
        
        #Check if Start/End of Celestial exists in Constellation-Dataset
        hasstart = (joined[joined["Cst"] == starsign]["Bayer"] == item[0]).any()
        hasend = (joined[joined["Cst"] == starsign]["Bayer"] == item[1]).any()
        
        if not (hasstart and hasend):
            print(f"FAILURE: Starsign {starsign} has no star {item}!")

In [18]:
#Collects the Start-HD-Index of each Connection
from_HD = []
#Collects the End-HD-Index of each Connection
to_HD = []
#Collects each Celestial in Bayer-Notation (only Constellation, no stars)
cst = []

#For each Celestial
for key in conns_bayer.keys():
    
    #Gather all Connections in Celestial in Bayer-Notation
    connections = conns_bayer[key]
    #Gather all Stars in Celestial
    set_of_cst = joined[joined["Cst"] == key]
    
    #For each Connection in Bayer-Notation, gather HD-Index of Start/End of Connection
    #If duplicates occur, use the first Element
    for item in connections:
        from_HD.append(set_of_cst[set_of_cst["Bayer"] == item[0]].iloc[0]["HD"])
        to_HD.append(set_of_cst[set_of_cst["Bayer"] == item[1]].iloc[0]["HD"])
        cst.append(key)
        
conns_HD = pd.DataFrame(data={"From": from_HD, "To": to_HD, "Cst": cst})
conns_HD

       From      To  Cst
0     18884   18604  Cet
1     18604   17094  Cet
2     17094   15318  Cet
3     15318   16161  Cet
4     16161   16970  Cet
..      ...     ...  ...
649  216763  216956  PsA
650  177474  178253  CrA
651  178253  178345  CrA
652  178345  177873  CrA
653  177873  170845  CrA

[654 rows x 3 columns]

Translate `conns_HD` from HD-Indexing to HIP-Indexing
===
`conns_HD` contains all Connection with their Celestial in HD-Indexing

In [19]:
#Gather Translation-Table and set to HD-Indexing
hd_to_hip = joined.loc[:, ["HD"]]
hd_to_hip = hd_to_hip.reset_index()
hd_to_hip = hd_to_hip.set_index("HD")
hd_to_hip

             HIP
HD
18884    14135.0
18883    14143.0
19926    14915.0
18604    13954.0
21120    15900.0
...          ...
202753  105164.0
199960  103682.0
198571  102945.0
198667  103005.0
198026  102624.0

[3566 rows x 1 columns]

In [21]:
#Join HIP-Indexing to each Connection and rename Columns
conns_HD_HIP = conns_HD.join(hd_to_hip, how="left", on="From", validate="many_to_one")
conns_HD_HIP = conns_HD_HIP.rename(columns={"HIP": "From_HIP", "From": "From_HD"})
conns_HD_HIP = conns_HD_HIP.join(hd_to_hip, how="left", on="To", validate="many_to_one")
conns_HD_HIP = conns_HD_HIP.rename(columns={"HIP": "To_HIP", "To": "To_HD"})
conns_HD_HIP

     From_HD   To_HD  Cst  From_HIP    To_HIP
0      18884   18604  Cet   14135.0   13954.0
1      18604   17094  Cet   13954.0   12828.0
2      17094   15318  Cet   12828.0   11484.0
3      15318   16161  Cet   11484.0   12093.0
4      16161   16970  Cet   12093.0   12706.0
..       ...     ...  ...       ...       ...
649   216763  216956  PsA  113246.0  113368.0
650   177474  178253  CrA   93825.0   94114.0
651   178253  178345  CrA   94114.0   94160.0
652   178345  177873  CrA   94160.0   94005.0
653   177873  170845  CrA   94005.0   90982.0

[654 rows x 5 columns]

Export Connections-Dataset with HIP-Indices
===
(If needed, Export with HD-Indices is also supported)

In [22]:
conns_HD_HIP.loc[:, ["From_HIP", "To_HIP", "Cst"]].to_csv("conns_HIP.csv")
#conns_HD_HIP.loc[:, ["From_HD", "To_HD", "Cst"]].to_csv("conns_HD.csv")